import React from 'react';
import Link from 'next/link';
import styles from './PrivacyPolicy.module.css';

export const metadata = {
  title: 'HIPAA Privacy Policy & Notice of Privacy Practices | Delta Health Center',
  description: 'Learn how medical information about you may be used and disclosed and how you can get access to this information under HIPAA.',
};

export default function PrivacyPolicy() {
  return (
    <>
      <div className="container">
        <section className={styles.hero}>
          <img src="/images/provider_hero.png" alt="Privacy Policy Hero" className={styles.heroBg} />
          <div className={styles.heroOverlay}></div>
          <div className={styles.heroContent}>
            <h1 className={styles.heroTitle}>HIPAA Privacy Policy</h1>
            <p className={styles.heroSubtitle}>Notice of Privacy Practices for Delta Health Center</p>
          </div>
        </section>
      </div>

      <section className={styles.contentSection}>
        <div className="container">
          <div className={styles.containerBox}>
            <div className={styles.noticeBanner}>
              <p>
                THIS NOTICE DESCRIBES HOW MEDICAL INFORMATION ABOUT YOU MAY BE USED AND DISCLOSED AND HOW YOU CAN GET ACCESS TO THIS INFORMATION. PLEASE REVIEW IT CAREFULLY.
              </p>
            </div>

            <h2 className={styles.sectionTitle}>Our Pledge Regarding Medical Information</h2>
            <p className={styles.paragraph}>
              Delta Health Center understands that medical information about you and your health is personal. We are committed to protecting medical information about you. We create a record of the care and services you receive at Delta Health Center to provide you with quality care and to comply with certain legal requirements.
            </p>
            <p className={styles.paragraph}>
              This Notice applies to all of the records of your care generated by Delta Health Center, whether made by health center personnel, your personal doctor, or other healthcare professionals.
            </p>

            <h2 className={styles.sectionTitle}>How We May Use and Disclose Health Information</h2>
            <p className={styles.paragraph}>
              The following categories describe different ways that we use and disclose medical information. For each category, we explain what we mean and present examples:
            </p>

            <ul className={styles.list}>
              <li className={styles.listItem}>
                <strong>For Treatment:</strong> We may use medical information about you to provide you with healthcare treatment or services. We may disclose medical information about you to doctors, nurses, technicians, health students, or other personnel involved in taking care of you.
              </li>
              <li className={styles.listItem}>
                <strong>For Payment:</strong> We may use and disclose medical information about you so that the treatment and services you receive at Delta Health Center may be billed to and payment may be collected from you, an insurance company, Medicaid, Medicare, or a third party.
              </li>
              <li className={styles.listItem}>
                <strong>For Health Care Operations:</strong> We may use and disclose medical information about you for health center operations. These uses and disclosures are necessary to run Delta Health Center and make sure that all of our patients receive quality care.
              </li>
              <li className={styles.listItem}>
                <strong>Appointment Reminders & Service Information:</strong> We may use and disclose medical information to contact you as a reminder that you have an appointment or to inform you about treatment alternatives and health-related benefits.
              </li>
              <li className={styles.listItem}>
                <strong>As Required By Law:</strong> We will disclose medical information about you when required to do so by federal, state, or local law (such as reporting public health risks, abuse, or court orders).
              </li>
            </ul>

            <h2 className={styles.sectionTitle}>Your Health Information Rights</h2>
            <p className={styles.paragraph}>
              You have the following rights regarding medical information we maintain about you:
            </p>

            <ul className={styles.list}>
              <li className={styles.listItem}>
                <strong>Right to Inspect and Copy:</strong> You have the right to inspect and obtain a copy of medical information that may be used to make decisions about your care.
              </li>
              <li className={styles.listItem}>
                <strong>Right to Amend:</strong> If you feel that medical information we have about you is incorrect or incomplete, you may ask us to amend the information.
              </li>
              <li className={styles.listItem}>
                <strong>Right to an Accounting of Disclosures:</strong> You have the right to request an "accounting of disclosures." This is a list of disclosures we made of medical information about you.
              </li>
              <li className={styles.listItem}>
                <strong>Right to Request Restrictions:</strong> You have the right to request a restriction or limitation on the medical information we use or disclose about you for treatment, payment, or operations.
              </li>
              <li className={styles.listItem}>
                <strong>Right to a Paper Copy of This Notice:</strong> You have the right to a paper copy of this notice at any time upon request.
              </li>
            </ul>

            <h2 className={styles.sectionTitle}>Changes to This Privacy Notice</h2>
            <p className={styles.paragraph}>
              We reserve the right to change this notice. We reserve the right to make the revised or changed notice effective for medical information we already have about you as well as any information we receive in the future. We will post a copy of the current notice in our healthcare clinics and on our website.
            </p>

            <div className={styles.contactBox}>
              <h3>Complaints & Privacy Inquiries</h3>
              <p>
                If you believe your privacy rights have been violated, you may file a complaint with Delta Health Center or with the Secretary of the Department of Health and Human Services. All complaints must be submitted in writing. You will not be penalized for filing a complaint.
              </p>
              <p style={{ marginTop: '16px' }}>
                <strong>Delta Health Center Privacy Officer</strong>
              </p>
              <p>
                702 Martin Luther King Road, Mound Bayou, MS 38762
              </p>
              <p>
                <strong>Phone:</strong> <a href="tel:6627418800" style={{ color: 'var(--color-primary)', fontWeight: 600 }}>(662) 741-8800</a>
              </p>
              <p>
                <strong>Contact Form:</strong> You may also submit inquiries via our <Link href="/contact" style={{ color: 'var(--color-primary)', fontWeight: 600, textDecoration: 'underline' }}>Contact Form</Link>.
              </p>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
